name = "jkh-hospital-website"
main = "src/index.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "jkh-website-db"
database_id = "c16c01ca-b115-4ea9-9664-9e0b24279f15"
